name: Python Data Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data loader script
      run: |
        python Lab3-Analizator_wynikow.py

    - name: Upload README and plots as artifact
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: |
          README.md
          plot_*.png
